version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-22222}:27017"
    volumes:
      - /data/db
      - /data/configdb
    networks:
      - default

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 27127:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo
    networks:
      - default

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    networks:
      - default

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5430:80"
    volumes:
      - /var/lib/pgadmin
    environment:
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
    networks:
      - default
    depends_on:
      - postgres

  test-mongo:
    container_name: test-mongo
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-22222}:27017"
    volumes:
      - /data/db
      - /data/configdb
    networks:
      - test

  test-mongo-express:
    container_name: test-mongo-express
    image: mongo-express
    ports:
      - 27127:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://test-mongo:27017/
    depends_on:
      - test-mongo
    networks:
      - test

  test-postgres:
    container_name: test-postgres
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    networks:
      - test

  test-pgadmin:
    container_name: test-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5440:80"
    volumes:
      - /var/lib/pgadmin
    environment:
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
    networks:
      - test
    depends_on:
      - test-postgres

networks:
  default:
    driver: bridge
  test:
    driver: bridge
