version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - default

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5430:80"
    volumes:
      - pgadmin_data_volume:/var/lib/pgadmin
    environment:
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    networks:
      - default
    depends_on:
      - postgres

  test-postgres:
    container_name: test-postgres
    image: postgres:latest
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - test

  test-pgadmin:
    container_name: test-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5440:80"
    volumes:
      - test-pgadmin_data_volume:/var/lib/pgadmin
    environment:
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    networks:
      - test
    depends_on:
      - test-postgres

networks:
  default:
    driver: bridge
  test:
    driver: bridge

volumes:
  postgres_data_volume:
  pgadmin_data_volume:
  test-pgadmin_data_volume:
