---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#
# Great tricks:
# https://yonatankra.com/7-github-actions-tricks-i-wish-i-knew-before-i-started
#

#############################################################################
# Start the job on push to `main` branch or on pull request created/updated #
#############################################################################
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

##########################################################
# Stop previously running job if another new one started #
##########################################################
concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

###############
# Set the Job #
###############
jobs:
  build:
    if: github.event.act == true || github.event.pull_request.draft == false
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ##########################
      # Setup Node.js v14.19.0 #
      ##########################
      - name: Use Node.js 14.19.0
        uses: actions/setup-node@v2
        with:
          node-version: '14.19.0'

      ################
      # Install yarn #
      ################
      - name: Install yarn
        run: npm -g install yarn@1.22.18

      ##############################
      # Add cache for yarn modules #
      ##############################
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: iluvcofee-cache-yarn-${{ hashFiles('**/yarn.lock') }}

      ############################
      # Install all dependencies #
      ############################
      - name: Install all dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --freeze-lock --network-timeout 100000

      ################################
      # Run ESLint against code base #
      ################################
      - name: Lint Code Base
        run: yarn lint
